[minor_fixes] fixed one type hint
Because of that, the mypy was raising quite random errors like
src/sqlfluff/dialects/dialect_snowflake.py:890: error: Item 'None' of 'Optional[Matchable]' has no attribute 'copy'
src/sqlfluff/dialects/dialect_snowflake.py:1672: error: 'Type[BaseSegment]' has no attribute 'explainable_stmt'