fix/adding-missing-keyword-segments
These types are missing --> therefore the linter is failing with:
RuntimeError: Grammar refers to 'OrcKeywordSegment' which was not found in the athena dialect. Perhaps specify the keyword? https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes#keywords