Small refactor with type hints and string formattings (#1525)
* [minor_fixes] added some type hints in batch

* changed some '.format' into 'f-strings';
* fixed some typos;

* [minor_fixes] fixed one type hint

Because of that, the mypy was raising quite random errors like
src/sqlfluff/dialects/dialect_snowflake.py:890: error: Item 'None' of 'Optional[Matchable]' has no attribute 'copy'
src/sqlfluff/dialects/dialect_snowflake.py:1672: error: 'Type[BaseSegment]' has no attribute 'explainable_stmt'

* [minor_fixes] cr changes

* single quotes instead of 'repr';
* small refactor of parse function to solve problematic 'result' type hinting (mypy complaining);

* [minor_fixes] make a 'violations' function static back again to avoid any problems in future

* [minor_fixes] fix typo