Adding missing KeywordSegments for different file types in Athena dialect (#3898)
* fix/adding-missing-keyword-segments

These types are missing --> therefore the linter is failing with:
RuntimeError: Grammar refers to 'OrcKeywordSegment' which was not found in the athena dialect. Perhaps specify the keyword? https://github.com/sqlfluff/sqlfluff/wiki/Contributing-Dialect-Changes#keywords

* add test for athena orc file

* create yaml file

* test input format

Co-authored-by: CommonCrisis <samuel@Brudi.localdomain>
Co-authored-by: Barry Hart <barrywhart@yahoo.com>
Co-authored-by: Alan Cruickshank <alanmcruickshank@gmail.com>